import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Dinogame from '../components/game/dinogame'
import Score from '../components/score/score'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DinoDex | Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Lets Go!!
        </h1>
        <Score/>
        <div>
          <Dinogame />
        </div>
      </main>
    </div>
  )
}